// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Verdelak.Api.Data;

#nullable disable

namespace Verdelak.Api.Migrations
{
    [DbContext(typeof(VerdelakDbContext))]
    [Migration("20260825225000_NormalizeAlcoholInventoryApply")]
    partial class NormalizeAlcoholInventoryApply
    {
    }
}
