// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Verdelak.Api.Data;

#nullable disable

namespace Verdelak.Api.Migrations
{
    [DbContext(typeof(VerdelakDbContext))]
    [Migration("20260520143933_AddResumeTables")]
    partial class AddResumeTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Verdelak.Api.Models.AppUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("appUsers");
                });

            modelBuilder.Entity("Verdelak.Api.Models.BackupDestination", b =>
                {
                    b.Property<int>("DestinationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DestinationID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathOrURI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinationID");

                    b.ToTable("BackupDestinations");
                });

            modelBuilder.Entity("Verdelak.Api.Models.BackupJob", b =>
                {
                    b.Property<int>("BackupJobID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BackupJobID"));

                    b.Property<bool>("CompressionEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("DestinationID")
                        .HasColumnType("int");

                    b.Property<bool>("EncryptionEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastRun")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceID")
                        .HasColumnType("int");

                    b.Property<int>("TaskID")
                        .HasColumnType("int");

                    b.Property<bool>("VerifyAfterCopy")
                        .HasColumnType("bit");

                    b.HasKey("BackupJobID");

                    b.HasIndex("DestinationID");

                    b.HasIndex("SourceID");

                    b.HasIndex("TaskID");

                    b.ToTable("BackupJobs");
                });

            modelBuilder.Entity("Verdelak.Api.Models.BackupJobLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<int>("BackupJobID")
                        .HasColumnType("int");

                    b.Property<long?>("BytesCopied")
                        .HasColumnType("bigint");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OccurrenceID")
                        .HasColumnType("int");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("LogID");

                    b.HasIndex("BackupJobID");

                    b.HasIndex("OccurrenceID");

                    b.ToTable("BackupJobLogs");
                });

            modelBuilder.Entity("Verdelak.Api.Models.BackupSource", b =>
                {
                    b.Property<int>("SourceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SourceID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathOrURI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SourceID");

                    b.ToTable("BackupSources");
                });

            modelBuilder.Entity("Verdelak.Api.Models.BarcodeLookupCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarcodeStagingItemId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Format")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PublishDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Publisher")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RawJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Selected")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("BarcodeStagingItemId");

                    b.HasIndex("Provider");

                    b.HasIndex("Selected");

                    b.ToTable("BarcodeLookupCandidates", (string)null);
                });

            modelBuilder.Entity("Verdelak.Api.Models.BarcodeStagingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LookupProvider")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawLookupJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("SuggestedCreator")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SuggestedFormat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SuggestedTitle")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SuggestedYear")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Upc")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BatchName");

                    b.HasIndex("CodeType");

                    b.HasIndex("ItemType");

                    b.HasIndex("NormalizedCode");

                    b.HasIndex("Source");

                    b.HasIndex("Status");

                    b.HasIndex("Upc");

                    b.ToTable("BarcodeStagingItems", (string)null);
                });

            modelBuilder.Entity("Verdelak.Api.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PostedDate");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("BlogPosts", (string)null);
                });

            modelBuilder.Entity("Verdelak.Api.Models.BlogPostTag", b =>
                {
                    b.Property<int>("BlogPostId")
                        .HasColumnType("int");

                    b.Property<int>("BlogTagId")
                        .HasColumnType("int");

                    b.HasKey("BlogPostId", "BlogTagId");

                    b.HasIndex("BlogTagId");

                    b.ToTable("BlogPostTags", (string)null);
                });

            modelBuilder.Entity("Verdelak.Api.Models.BlogTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("BlogTags", (string)null);
                });

            modelBuilder.Entity("Verdelak.Api.Models.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.Property<int?>("SeriesID")
                        .HasColumnType("int");

                    b.Property<short?>("SeriesNumber")
                        .HasColumnType("smallint");

                    b.Property<int?>("SubSeriesID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ID");

                    b.HasIndex("AuthorID");

                    b.HasIndex("SeriesID");

                    b.HasIndex("SubSeriesID");

                    b.HasIndex("Title");

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("Verdelak.Api.Models.BookAuthor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Fname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Middle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("BookAuthors", (string)null);
                });

            modelBuilder.Entity("Verdelak.Api.Models.BookFormat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("BookFormats", (string)null);
                });

            modelBuilder.Entity("Verdelak.Api.Models.BookSeries", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("BookSeries", (string)null);
                });

            modelBuilder.Entity("Verdelak.Api.Models.BookStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BooksID")
                        .HasColumnType("int");

                    b.Property<int>("FormatID")
                        .HasColumnType("int");

                    b.Property<string>("WantStatusID")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.HasKey("ID");

                    b.HasIndex("BooksID")
                        .IsUnique();

                    b.HasIndex("FormatID");

                    b.HasIndex("WantStatusID");

                    b.ToTable("BookStatus", (string)null);
                });

            modelBuilder.Entity("Verdelak.Api.Models.BookSubSeries", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("SeriesID")
                        .HasColumnType("int");

                    b.Property<string>("SubSeries")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("SeriesID");

                    b.ToTable("BookSubSeries", (string)null);
                });

            modelBuilder.Entity("Verdelak.Api.Models.Game", b =>
                {
                    b.Property<int>("GameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameID"));

                    b.Property<decimal?>("BGG_Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BaseGameID")
                        .HasColumnType("int");

                    b.Property<bool>("IsExpansion")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Owns")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PersonalRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Wishlist")
                        .HasColumnType("bit");

                    b.HasKey("GameID");

                    b.HasIndex("BaseGameID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Verdelak.Api.Models.GamePlay", b =>
                {
                    b.Property<int>("PlayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayID"));

                    b.Property<int>("GameID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlayDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PlayID");

                    b.HasIndex("GameID");

                    b.ToTable("GamePlays");
                });

            modelBuilder.Entity("Verdelak.Api.Models.HomeInventoryImage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ItemID");

                    b.ToTable("HomeInventoryImages", (string)null);
                });

            modelBuilder.Entity("Verdelak.Api.Models.HomeInventoryItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EstimatedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MakeModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PurchaseLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("RoomId");

                    b.ToTable("HomeInventoryItems", (string)null);
                });

            modelBuilder.Entity("Verdelak.Api.Models.HomeInventoryNote", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("NoteNum")
                        .HasColumnType("smallint");

                    b.Property<short>("NotePartNum")
                        .HasColumnType("smallint");

                    b.HasKey("ID");

                    b.HasIndex("ItemID");

                    b.ToTable("HomeInventoryNotes", (string)null);
                });

            modelBuilder.Entity("Verdelak.Api.Models.Link", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubTopicID")
                        .HasColumnType("int");

                    b.Property<int?>("TopicID")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerificationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("SubTopicID");

                    b.HasIndex("TopicID");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("Verdelak.Api.Models.LinkSubTopic", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("SubTopic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TopicID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TopicID");

                    b.ToTable("LinkSubTopics");
                });

            modelBuilder.Entity("Verdelak.Api.Models.LinkTopic", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("LinkTopics");
                });

            modelBuilder.Entity("Verdelak.Api.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location");

                    b.HasKey("ID");

                    b.ToTable("Location", (string)null);
                });

            modelBuilder.Entity("Verdelak.Api.Models.MusicAlbum", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ArtistID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ArtistID");

                    b.ToTable("MusicAlbum");
                });

            modelBuilder.Entity("Verdelak.Api.Models.MusicAlbumInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AlbumID")
                        .HasColumnType("int");

                    b.Property<string>("Format")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasDefaultValue("CD");

                    b.Property<string>("InfoText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("AlbumID")
                        .IsUnique();

                    b.ToTable("MusicAlbumInfos");
                });

            modelBuilder.Entity("Verdelak.Api.Models.MusicAlbumStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AlbumID")
                        .HasColumnType("int");

                    b.Property<string>("FormatID")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char(2)");

                    b.Property<string>("WantStatusID")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.HasKey("ID");

                    b.HasIndex("AlbumID")
                        .IsUnique();

                    b.HasIndex("WantStatusID");

                    b.ToTable("MusicAlbumStatus", (string)null);
                });

            modelBuilder.Entity("Verdelak.Api.Models.MusicArtist", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("MusicArtist");
                });

            modelBuilder.Entity("Verdelak.Api.Models.MusicArtistBio", b =>
                {
                    b.Property<int>("ArtistID")
                        .HasColumnType("int");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BioText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("ArtistID");

                    b.ToTable("MusicArtistBios");
                });

            modelBuilder.Entity("Verdelak.Api.Models.RPGProduct", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Edition")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .IsFixedLength(false);

                    b.Property<string>("ISBN")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .IsFixedLength(false);

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("SeriesID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SystemID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProductName");

                    b.HasIndex("ProductTypeID");

                    b.HasIndex("SeriesID");

                    b.HasIndex("SystemID");

                    b.ToTable("RPGProduct", "dbo");
                });

            modelBuilder.Entity("Verdelak.Api.Models.RPGProductType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("RPGProductType", "dbo");
                });

            modelBuilder.Entity("Verdelak.Api.Models.RPGSeries", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("SeriesName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("SeriesName")
                        .IsUnique();

                    b.ToTable("RPGSeries", "dbo");
                });

            modelBuilder.Entity("Verdelak.Api.Models.RPGSeriesNote", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RPGSeriesID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RPGSeriesID");

                    b.ToTable("RPGSeriesNotes", "dbo");
                });

            modelBuilder.Entity("Verdelak.Api.Models.RPGSystem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RPGSystem", "dbo");
                });

            modelBuilder.Entity("Verdelak.Api.Models.RPGSystemNote", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RPGSystemID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RPGSystemID");

                    b.ToTable("RPGSystemNotes", "dbo");
                });

            modelBuilder.Entity("Verdelak.Api.Models.ResumeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("StartText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TagsCsv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Section");

                    b.HasIndex("SortOrder");

                    b.ToTable("ResumeItems", (string)null);
                });

            modelBuilder.Entity("Verdelak.Api.Models.ResumeProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("ResumeProfiles", (string)null);
                });

            modelBuilder.Entity("Verdelak.Api.Models.Review", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AlbumID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerID")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AlbumID");

                    b.HasIndex("ReviewerID");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("Verdelak.Api.Models.ScheduledTask", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastGenerated")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecurrencePattern")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScheduleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskID");

                    b.ToTable("ScheduledTasks");
                });

            modelBuilder.Entity("Verdelak.Api.Models.ScheduledTaskTag", b =>
                {
                    b.Property<int>("TaskID")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ScheduledTaskTaskID")
                        .HasColumnType("int");

                    b.HasKey("TaskID", "Tag");

                    b.HasIndex("ScheduledTaskTaskID");

                    b.ToTable("ScheduledTaskTags");
                });

            modelBuilder.Entity("Verdelak.Api.Models.SchedulerRunHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastRunDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SchedulerRunHistory");
                });

            modelBuilder.Entity("Verdelak.Api.Models.Spookytown", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Own")
                        .HasColumnType("bit");

                    b.Property<short?>("Qty")
                        .HasColumnType("smallint");

                    b.Property<bool?>("Retired")
                        .HasColumnType("bit");

                    b.Property<string>("SKU")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TypeId")
                        .HasColumnType("nchar(1)")
                        .HasColumnName("TypeID");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("URL");

                    b.Property<bool>("Want")
                        .HasColumnType("bit");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Spookytown", (string)null);
                });

            modelBuilder.Entity("Verdelak.Api.Models.SpookytownType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nchar(1)")
                        .HasColumnName("ID");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SpookytownType", (string)null);
                });

            modelBuilder.Entity("Verdelak.Api.Models.TaskOccurrence", b =>
                {
                    b.Property<int>("OccurrenceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OccurrenceID"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskID")
                        .HasColumnType("int");

                    b.HasKey("OccurrenceID");

                    b.HasIndex("TaskID");

                    b.ToTable("TaskOccurrences");
                });

            modelBuilder.Entity("Verdelak.Api.Models.BackupJob", b =>
                {
                    b.HasOne("Verdelak.Api.Models.BackupDestination", "BackupDestination")
                        .WithMany()
                        .HasForeignKey("DestinationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Verdelak.Api.Models.BackupSource", "BackupSource")
                        .WithMany()
                        .HasForeignKey("SourceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Verdelak.Api.Models.ScheduledTask", "ScheduledTask")
                        .WithMany()
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BackupDestination");

                    b.Navigation("BackupSource");

                    b.Navigation("ScheduledTask");
                });

            modelBuilder.Entity("Verdelak.Api.Models.BackupJobLog", b =>
                {
                    b.HasOne("Verdelak.Api.Models.BackupJob", "BackupJob")
                        .WithMany()
                        .HasForeignKey("BackupJobID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Verdelak.Api.Models.TaskOccurrence", "TaskOccurrence")
                        .WithMany()
                        .HasForeignKey("OccurrenceID");

                    b.Navigation("BackupJob");

                    b.Navigation("TaskOccurrence");
                });

            modelBuilder.Entity("Verdelak.Api.Models.BarcodeLookupCandidate", b =>
                {
                    b.HasOne("Verdelak.Api.Models.BarcodeStagingItem", "BarcodeStagingItem")
                        .WithMany("LookupCandidates")
                        .HasForeignKey("BarcodeStagingItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BarcodeStagingItem");
                });

            modelBuilder.Entity("Verdelak.Api.Models.BlogPostTag", b =>
                {
                    b.HasOne("Verdelak.Api.Models.BlogPost", "BlogPost")
                        .WithMany("BlogPostTags")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Verdelak.Api.Models.BlogTag", "BlogTag")
                        .WithMany("BlogPostTags")
                        .HasForeignKey("BlogTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogPost");

                    b.Navigation("BlogTag");
                });

            modelBuilder.Entity("Verdelak.Api.Models.Book", b =>
                {
                    b.HasOne("Verdelak.Api.Models.BookAuthor", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Verdelak.Api.Models.BookSeries", "Series")
                        .WithMany("Books")
                        .HasForeignKey("SeriesID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Verdelak.Api.Models.BookSubSeries", "SubSeries")
                        .WithMany("Books")
                        .HasForeignKey("SubSeriesID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");

                    b.Navigation("Series");

                    b.Navigation("SubSeries");
                });

            modelBuilder.Entity("Verdelak.Api.Models.BookStatus", b =>
                {
                    b.HasOne("Verdelak.Api.Models.Book", "Book")
                        .WithOne("Status")
                        .HasForeignKey("Verdelak.Api.Models.BookStatus", "BooksID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Verdelak.Api.Models.BookFormat", "Format")
                        .WithMany("BookStatuses")
                        .HasForeignKey("FormatID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Format");
                });

            modelBuilder.Entity("Verdelak.Api.Models.BookSubSeries", b =>
                {
                    b.HasOne("Verdelak.Api.Models.BookSeries", "Series")
                        .WithMany("SubSeries")
                        .HasForeignKey("SeriesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Verdelak.Api.Models.Game", b =>
                {
                    b.HasOne("Verdelak.Api.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("BaseGameID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Verdelak.Api.Models.GamePlay", b =>
                {
                    b.HasOne("Verdelak.Api.Models.Game", "Game")
                        .WithMany("GamePlays")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Verdelak.Api.Models.HomeInventoryImage", b =>
                {
                    b.HasOne("Verdelak.Api.Models.HomeInventoryItem", "Item")
                        .WithMany("Images")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Verdelak.Api.Models.HomeInventoryItem", b =>
                {
                    b.HasOne("Verdelak.Api.Models.Location", "Room")
                        .WithMany("Items")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Verdelak.Api.Models.HomeInventoryNote", b =>
                {
                    b.HasOne("Verdelak.Api.Models.HomeInventoryItem", "Item")
                        .WithMany("Notes")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Verdelak.Api.Models.Link", b =>
                {
                    b.HasOne("Verdelak.Api.Models.LinkSubTopic", "SubTopic")
                        .WithMany("Links")
                        .HasForeignKey("SubTopicID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Verdelak.Api.Models.LinkTopic", "Topic")
                        .WithMany("Links")
                        .HasForeignKey("TopicID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("SubTopic");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Verdelak.Api.Models.LinkSubTopic", b =>
                {
                    b.HasOne("Verdelak.Api.Models.LinkTopic", "Topic")
                        .WithMany("SubTopics")
                        .HasForeignKey("TopicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Verdelak.Api.Models.MusicAlbum", b =>
                {
                    b.HasOne("Verdelak.Api.Models.MusicArtist", "Band")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Band");
                });

            modelBuilder.Entity("Verdelak.Api.Models.MusicAlbumInfo", b =>
                {
                    b.HasOne("Verdelak.Api.Models.MusicAlbum", "Album")
                        .WithOne("Info")
                        .HasForeignKey("Verdelak.Api.Models.MusicAlbumInfo", "AlbumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Verdelak.Api.Models.MusicAlbumStatus", b =>
                {
                    b.HasOne("Verdelak.Api.Models.MusicAlbum", "Album")
                        .WithOne("Status")
                        .HasForeignKey("Verdelak.Api.Models.MusicAlbumStatus", "AlbumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Verdelak.Api.Models.MusicArtistBio", b =>
                {
                    b.HasOne("Verdelak.Api.Models.MusicArtist", "Artist")
                        .WithOne("Bio")
                        .HasForeignKey("Verdelak.Api.Models.MusicArtistBio", "ArtistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Verdelak.Api.Models.RPGProduct", b =>
                {
                    b.HasOne("Verdelak.Api.Models.RPGProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Verdelak.Api.Models.RPGSeries", "Series")
                        .WithMany("Products")
                        .HasForeignKey("SeriesID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Verdelak.Api.Models.RPGSystem", "System")
                        .WithMany("Products")
                        .HasForeignKey("SystemID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProductType");

                    b.Navigation("Series");

                    b.Navigation("System");
                });

            modelBuilder.Entity("Verdelak.Api.Models.RPGSeriesNote", b =>
                {
                    b.HasOne("Verdelak.Api.Models.RPGSeries", "Series")
                        .WithMany("Notes")
                        .HasForeignKey("RPGSeriesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Verdelak.Api.Models.RPGSystemNote", b =>
                {
                    b.HasOne("Verdelak.Api.Models.RPGSystem", "System")
                        .WithMany("Notes")
                        .HasForeignKey("RPGSystemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("Verdelak.Api.Models.Review", b =>
                {
                    b.HasOne("Verdelak.Api.Models.MusicAlbum", "Album")
                        .WithMany("Reviews")
                        .HasForeignKey("AlbumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Verdelak.Api.Models.AppUser", "Reviewer")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Verdelak.Api.Models.ScheduledTaskTag", b =>
                {
                    b.HasOne("Verdelak.Api.Models.ScheduledTask", "ScheduledTask")
                        .WithMany("Tags")
                        .HasForeignKey("ScheduledTaskTaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledTask");
                });

            modelBuilder.Entity("Verdelak.Api.Models.Spookytown", b =>
                {
                    b.HasOne("Verdelak.Api.Models.SpookytownType", "Type")
                        .WithMany("Items")
                        .HasForeignKey("TypeId");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Verdelak.Api.Models.TaskOccurrence", b =>
                {
                    b.HasOne("Verdelak.Api.Models.ScheduledTask", "ScheduledTask")
                        .WithMany("Occurrences")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledTask");
                });

            modelBuilder.Entity("Verdelak.Api.Models.AppUser", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Verdelak.Api.Models.BarcodeStagingItem", b =>
                {
                    b.Navigation("LookupCandidates");
                });

            modelBuilder.Entity("Verdelak.Api.Models.BlogPost", b =>
                {
                    b.Navigation("BlogPostTags");
                });

            modelBuilder.Entity("Verdelak.Api.Models.BlogTag", b =>
                {
                    b.Navigation("BlogPostTags");
                });

            modelBuilder.Entity("Verdelak.Api.Models.Book", b =>
                {
                    b.Navigation("Status");
                });

            modelBuilder.Entity("Verdelak.Api.Models.BookAuthor", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Verdelak.Api.Models.BookFormat", b =>
                {
                    b.Navigation("BookStatuses");
                });

            modelBuilder.Entity("Verdelak.Api.Models.BookSeries", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("SubSeries");
                });

            modelBuilder.Entity("Verdelak.Api.Models.BookSubSeries", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Verdelak.Api.Models.Game", b =>
                {
                    b.Navigation("GamePlays");
                });

            modelBuilder.Entity("Verdelak.Api.Models.HomeInventoryItem", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Verdelak.Api.Models.LinkSubTopic", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("Verdelak.Api.Models.LinkTopic", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("SubTopics");
                });

            modelBuilder.Entity("Verdelak.Api.Models.Location", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Verdelak.Api.Models.MusicAlbum", b =>
                {
                    b.Navigation("Info");

                    b.Navigation("Reviews");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Verdelak.Api.Models.MusicArtist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Bio");
                });

            modelBuilder.Entity("Verdelak.Api.Models.RPGProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Verdelak.Api.Models.RPGSeries", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Verdelak.Api.Models.RPGSystem", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Verdelak.Api.Models.ScheduledTask", b =>
                {
                    b.Navigation("Occurrences");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Verdelak.Api.Models.SpookytownType", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
